# Generated by Django 3.0.5 on 2021-04-28 08:06

from django.db import migrations, models
import djongo.models.fields
import parse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboAnalyseItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('search_content', models.CharField(max_length=20)),
                ('search_patch', models.IntegerField()),
                ('parse_time', models.CharField(max_length=20)),
                ('mid', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('comments_count', models.IntegerField()),
                ('res_count', djongo.models.fields.ArrayField(model_container=parse.models.ResCount)),
                ('res_spirit', djongo.models.fields.EmbeddedField(model_container=parse.models.ResSpirit)),
            ],
            options={
                'db_table': 'Analyse_Weibo',
            },
        ),
        migrations.CreateModel(
            name='WeiboHotItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ranking', models.CharField(max_length=5, verbose_name='排名')),
                ('content', models.TextField(verbose_name='内容')),
                ('count', models.CharField(max_length=10, verbose_name='热度')),
                ('desc', models.CharField(max_length=20, verbose_name='热度描述')),
            ],
            options={
                'verbose_name': '微博排名信息',
                'db_table': 'WeiboHot',
            },
        ),
        migrations.CreateModel(
            name='ZhiHuTopItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ranking', models.CharField(max_length=5, verbose_name='排名')),
                ('content', models.TextField(verbose_name='内容')),
                ('count', models.CharField(max_length=10, verbose_name='热度')),
            ],
            options={
                'verbose_name': '知乎排名信息',
                'db_table': 'ZhihuHot',
            },
        ),
    ]
