# Generated by Django 3.0.5 on 2021-05-02 01:57

from django.db import migrations, models
import djongo.models.fields
import parse.models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboHotsItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('hots', djongo.models.fields.ArrayField(model_container=parse.models.WeiboHotItem)),
            ],
            options={
                'verbose_name': '微博排名信息',
                'db_table': 'WeiboHots',
            },
        ),
        migrations.CreateModel(
            name='ZhihuHotsItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('hots', djongo.models.fields.ArrayField(model_container=parse.models.ZhihuHotItem)),
            ],
            options={
                'verbose_name': '知乎排名信息',
                'db_table': 'ZhihuHots',
            },
        ),
        migrations.DeleteModel(
            name='WeiboHotItem',
        ),
        migrations.DeleteModel(
            name='ZhiHuTopItem',
        ),
    ]
