# Generated by Django 3.0.5 on 2021-05-02 02:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20210502_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountHot',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('parse_type', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': '排行计数',
                'db_table': 'CountHot',
            },
        ),
        migrations.AlterModelOptions(
            name='weibohotsitem',
            options={'get_latest_by': 'time', 'verbose_name': '微博排名信息'},
        ),
    ]
