# Generated by Django 3.0.5 on 2021-05-04 02:06

from django.db import migrations, models
import djongo.models.fields
import parse.models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_searchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboAnalysesItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('search_content', models.CharField(max_length=20)),
                ('search_patch', models.IntegerField()),
                ('parse_time', models.CharField(max_length=20)),
                ('weibos', djongo.models.fields.ArrayField(model_container=parse.models.WeiboAnalyseItem)),
            ],
            options={
                'db_table': 'Analyse_Weibo',
            },
        ),
        migrations.DeleteModel(
            name='WeiboAnalyseItem',
        ),
    ]
